### ISSUE TITLE
Fails to read mcmod.info

### ISSUE THREAD

**Issue by TheRandomLabs** [MinimumContent/muon#2]
http://pastebin.com/5HHUHrBT
It doesn't crash the game though.

**Comment by TrinaryLogic** [comment]
This is a known issue due to be fixed in the next release. You're correct that it's primarily a cosmetic bug and does not affect the mod's operation. Thanks for the bug report!

**Comment by TrinaryLogic** [comment]
Muon 0.2 has finally been released and contains the fix for this issue. It will be available on Curseforge soon :)
